//! Helper functions used across the wiring layer.
//!
//! These functions used to live at the bottom of `main.rs`. Moving them
//! here keeps `main.rs` focused on setup and callback registration, and
//! lets each helper be unit-tested in isolation when needed.
//!
//! Most helpers are pure conversions (`task_to_card`, `label_to_pill`,
//! `parse_hex_rgb`) or display formatters (`format_tokens`, `format_cost`,
//! `format_runtime`, `format_relative_time`).

use std::path::{Path, PathBuf};
use std::rc::Rc;

use slint::{Model, ModelRc, SharedString, VecModel};

use crate::editor::EditorBuffer;
use crate::kanban::{Label, Task, TaskKind};
// Bridge structs generated by `slint::include_modules!()` in main.rs.
// They live in the crate root, so we re-import them here.
use crate::{HighlightedLineData, HlSpanData, LabelPillData, TaskCardData};

// ─── Conversions ────────────────────────────────────────────────────────────

pub fn task_to_card(
    task: &Task,
    display_id: i32,
    running: bool,
    dirty: bool,
    labels: Vec<LabelPillData>,
    blocked_count: i32,
) -> TaskCardData {
    let kind = TaskKind::from_title(&task.title);
    TaskCardData {
        id: SharedString::from(task.id.to_string()),
        display_id,
        title: SharedString::from(task.title.as_str()),
        kind: SharedString::from(kind_to_str(kind)),
        running,
        dirty,
        labels: ModelRc::from(Rc::new(VecModel::from(labels))),
        blocked_count,
        // Polish 22: drives the spinner-vs-static-dot decision in CardRow.
        session_state: SharedString::from(task.session_state.as_str()),
    }
}

pub fn kind_to_str(kind: TaskKind) -> &'static str {
    match kind {
        TaskKind::Enhancement => "enhancement",
        TaskKind::Feature => "feature",
        TaskKind::Bug => "bug",
    }
}

/// Convert a `Label` DB record into the Slint-side `LabelPillData`,
/// parsing the `#rrggbb` hex into separate 8-bit components because
/// Slint has no built-in string-to-brush conversion.
pub fn label_to_pill(label: &Label) -> LabelPillData {
    let (r, g, b) = parse_hex_rgb(&label.color).unwrap_or((167, 175, 184));
    LabelPillData {
        id: SharedString::from(label.id.to_string()),
        name: SharedString::from(label.name.as_str()),
        color_r: r as i32,
        color_g: g as i32,
        color_b: b as i32,
    }
}

/// Parse `#rrggbb` → `(r, g, b)` 8-bit components. Returns None on any
/// parse error (malformed length, bad hex digits, etc.) so the caller
/// can fall back to a default colour.
pub fn parse_hex_rgb(hex: &str) -> Option<(u8, u8, u8)> {
    let s = hex.strip_prefix('#').unwrap_or(hex);
    if s.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&s[0..2], 16).ok()?;
    let g = u8::from_str_radix(&s[2..4], 16).ok()?;
    let b = u8::from_str_radix(&s[4..6], 16).ok()?;
    Some((r, g, b))
}

// ─── Slint model helpers ────────────────────────────────────────────────────

/// Drain a `VecModel` and re-push every entry from `items`. Used to refresh
/// every list-shaped Slint binding (kanban columns, diff files, commit log)
/// from the latest snapshot. Generic over the row type so the same helper
/// covers `TaskCardData`, `DiffFileData`, `CommitEntryData`, etc.
pub fn replace_model<T: Clone + 'static>(model: &Rc<VecModel<T>>, items: Vec<T>) {
    while model.row_count() > 0 {
        model.remove(model.row_count() - 1);
    }
    for item in items {
        model.push(item);
    }
}

/// Polish 5: rebuild the `editor-highlighted-lines` VecModel from the
/// current buffer. Caps at `MAX_PREVIEW_LINES` so huge files don't
/// stall the UI. Called on open and on save.
pub const MAX_PREVIEW_LINES: usize = 500;

pub fn rebuild_editor_highlight(
    buffer: &EditorBuffer,
    model: &Rc<VecModel<HighlightedLineData>>,
) {
    while model.row_count() > 0 {
        model.remove(model.row_count() - 1);
    }
    let total = buffer.line_count();
    let render_count = total.min(MAX_PREVIEW_LINES);
    for i in 0..render_count {
        let spans = buffer.highlight_line(i);
        let spans_model = Rc::new(VecModel::<HlSpanData>::default());
        for s in spans {
            spans_model.push(HlSpanData {
                text: SharedString::from(s.text),
                color_r: s.r as i32,
                color_g: s.g as i32,
                color_b: s.b as i32,
                bold: s.bold,
                italic: s.italic,
            });
        }
        model.push(HighlightedLineData {
            line_no: (i + 1) as i32,
            spans: ModelRc::from(spans_model),
        });
    }
}

/// Heuristic: is this path likely a binary file the inline editor
/// should not try to load? Checks the extension against a short list;
/// returns true for common binary formats. False positives (e.g. a
/// user's `.dat` text file) are acceptable — they just fall back to
/// $EDITOR.
pub fn is_likely_binary(path: &Path) -> bool {
    let Some(ext) = path.extension().and_then(|e| e.to_str()) else {
        return false;
    };
    matches!(
        ext.to_ascii_lowercase().as_str(),
        "png"
            | "jpg"
            | "jpeg"
            | "gif"
            | "webp"
            | "bmp"
            | "ico"
            | "pdf"
            | "zip"
            | "gz"
            | "bz2"
            | "xz"
            | "7z"
            | "tar"
            | "exe"
            | "dll"
            | "so"
            | "dylib"
            | "bin"
            | "ttf"
            | "otf"
            | "woff"
            | "woff2"
            | "wasm"
            | "mp3"
            | "mp4"
            | "mkv"
            | "mov"
            | "avi"
            | "flac"
            | "ogg"
            | "webm"
    )
}

// ─── Display formatters ─────────────────────────────────────────────────────

/// Polish 15 — compact token count: 1_234 → "1.2k tok", 3_450_000 → "3.4M tok".
/// The `◇` glyph sits in the chip to echo Claude Code's own transcript marker.
pub fn format_tokens(n: u64) -> String {
    if n >= 1_000_000 {
        format!("◇ {:.1}M tok", n as f64 / 1_000_000.0)
    } else if n >= 1_000 {
        format!("◇ {:.1}k tok", n as f64 / 1_000.0)
    } else {
        format!("◇ {n} tok")
    }
}

/// Polish 15 — cost in cents → "$0.04" / "$12.35". Sub-cent totals
/// stay at "$0.00" to keep the chip width stable.
pub fn format_cost(cents: u64) -> String {
    let dollars = cents / 100;
    let remainder = cents % 100;
    format!("$ {dollars}.{remainder:02}")
}

/// Polish 15 — runtime in seconds → "42s" / "7m 12s" / "2h 03m".
pub fn format_runtime(secs: u64) -> String {
    if secs < 60 {
        format!("⏱ {secs}s")
    } else if secs < 3600 {
        let m = secs / 60;
        let s = secs % 60;
        format!("⏱ {m}m {s:02}s")
    } else {
        let h = secs / 3600;
        let m = (secs % 3600) / 60;
        format!("⏱ {h}h {m:02}m")
    }
}

/// Human-friendly relative time for commit timestamps.
/// "just now" · "3m ago" · "2h ago" · "4d ago".
pub fn format_relative_time(commit_time_secs: i64) -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let now_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    let delta = now_secs.saturating_sub(commit_time_secs);
    if delta < 30 {
        "just now".into()
    } else if delta < 3600 {
        format!("{}m ago", delta / 60)
    } else if delta < 86400 {
        format!("{}h ago", delta / 3600)
    } else if delta < 7 * 86400 {
        format!("{}d ago", delta / 86400)
    } else {
        // Fall back to a YYYY-MM-DD-ish rendering using the absolute time.
        // We avoid pulling in chrono for this — a crude div/mod is fine.
        let days_since_epoch = commit_time_secs / 86400;
        format!("~{days_since_epoch} days since epoch")
    }
}

// ─── Platform glue ──────────────────────────────────────────────────────────

#[cfg(unix)]
pub fn default_shell() -> (String, String) {
    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/sh".into());
    let label = Path::new(&shell)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("sh")
        .to_string();
    (shell, label)
}

#[cfg(windows)]
pub fn default_shell() -> (String, String) {
    ("powershell.exe".to_string(), "powershell".to_string())
}

/// Returns the working directory Quay was launched from. This is used
/// as the default CWD for tasks when no project is selected — much
/// safer than `$HOME` because it scopes agents to the directory the
/// user explicitly chose to run Quay from.
pub fn home_directory() -> PathBuf {
    std::env::current_dir().unwrap_or_else(|_| {
        directories::UserDirs::new()
            .map(|d| d.home_dir().to_path_buf())
            .unwrap_or_else(|| PathBuf::from("."))
    })
}

/// Rebuild the sidebar menu model with freshly-translated labels.
/// Called when the user changes the locale at runtime so the sidebar
/// text updates without restarting.
pub fn rebuild_menu_model(window: &crate::MainWindow) {
    use crate::MenuItemData;
    let model = Rc::new(VecModel::<MenuItemData>::default());
    for (id, glyph, label, shortcut) in [
        ("new-task",      "",  t!("menu.new_cli_session").to_string(), "".to_string()),
        ("quick-action",  "",  t!("menu.quick_action").to_string(),    "submenu".to_string()),
        ("configure",     "",  t!("menu.configure").to_string(),       "".to_string()),
        ("sessions",      "",  t!("menu.sessions").to_string(),        "".to_string()),
        ("worktrees",     "",  t!("menu.worktrees").to_string(),       "".to_string()),
    ] {
        model.push(MenuItemData {
            id: id.into(),
            glyph: glyph.into(),
            label: SharedString::from(label),
            shortcut: SharedString::from(shortcut),
        });
    }
    window.set_menu_items(ModelRc::from(model));
}
